// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Practice Next.js Scode",
  description: "Generated by Hasan Smajlovic",
};

export default function RootLayout({ children, header, footer }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable}`}
      >
        {header}
        {children}
        {footer}
      </body>
    </html>
  );
}
