import PropTypes from 'prop-types'

import './globals.css'

export const metadata = {
  title       : 'Practice Next.js Scode',
  description : 'Generated by Hasan Smajlovic'
}

export default function RootLayout ({ children, header, footer }) {
  return (
    <html lang='en'>
      <body>
        {header}
        {children}
        {footer}
      </body>
    </html>
  )
}

RootLayout.propTypes = {
  children : PropTypes.node,
  header   : PropTypes.node,
  footer   : PropTypes.node
}
